name: Build and Deploy Spring JWT
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy spring for beginners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKER_USERNAME }}/social-login:latest

        - name: Login to docker hub
            - uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME}}
                password: ${{ secrets.DOCKER_PASSWORD}}

        - name: Push to Docker hub
          uses: docker/build-push-action@v2
          context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/social-login:latest



